language: generic
script: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
before_install:
  openssl aes-256-cbc -K $encrypted_e69766e2a2e2_key -iv $encrypted_e69766e2a2e2_iv -in id_rsa_travis_ci.enc -out id_rsa_travis_ci -d
